# Generated by Django 5.2.6 on 2025-11-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuarios_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('puiblicador', 'Publicador'), ('adoptante', 'Adoptante')], default='adoptante', max_length=20),
        ),
    ]
