# Generated by Django 5.2.6 on 2025-11-04 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('publicador', 'Publicador'), ('adoptante', 'Adoptante')], default='adoptante', max_length=20),
        ),
    ]
